name = "PubMedMiner"
uuid = "46dc0c4a-6509-5e23-bf4c-54ba737af988"
author = ["Brown Center for Biomedical Informatics"]
version = "0.0.0"

[deps]
ARules = "7cbe2057-1070-5a1a-9a20-8e476bfa53e1"
BCBIStats = "90663416-1ff1-5773-9c80-87bbd7add2fc"
BioMedQuery = "e96904bf-1073-5077-9b57-b0ce0ff5555a"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FreqTables = "da1fdf0e-e0ff-5433-a45f-9bb5ff651cb1"
MySQL = "39abe10b-433b-5dbd-92d4-e302a9df00cd"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
